### ISSUE TITLE
The Canonical Registration Requirements Checklist! ☑

### ISSUE THREAD

**Issue by kurtlewis** [RevolutionUC/revolutionuc-website#126]
List of requirements for registration this time around. Will update if anymore arise.

In some cases, there might be a document that needs linked that I won't be able to link since this is public. I'll note where to find it if so
- [x] Food restrictions - we had a fill in box which was lead to non-standard responses. Lets do check boxes (so more than one can be clicked) for the following: `vegetarian` `vegan` `nut(peanut, tree nut, etc) allergy`, and a text box for others
- [x] Did whatever field went into `accommodations` actually lead to anything meaningful? It does not seem so from looking at registration data
- [ ] login/key for MLH to read the database in a read only mode
- [x] (if we don't have it) a check box... "I agree to MLH code of conduct" with link. required.
- [x] required check box - [MLH Data sharing - text as in this link](https://github.com/MLH/mlh-policies/blob/master/data-sharing.md)
- [x] We want to provide you faster insights and analytics on your event and scoring for the end of season winner.  To do this, we need your help to normalize your school name data collection. Please use our provided  list of schools to create a drop down question on your registration form to indicate which school your attendees are coming from.  [Link](https://github.com/MLH/mlh-policies/blob/master/schools.csv)
- [x] MLH required fields which we probably already have `first name`, `last name`, `email`, `school`, `phone #`(make sure you save it ;) ), `demographic information`

Will add things if they come up!
